#Minecraft server properties
#Sun Sep 13 20:09:28 TRT 2026
enable-jmx-monitoring=false
level-seed=
management-server-port=0
rcon.port=25575
enable-command-block=false
gamemode=survival
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
text-filtering-version=0
motd=A Minecraft Server
pause-when-empty-seconds=60
management-server-host=localhost
query.port=25566
management-server-tls-enabled=true
management-server-tls-keystore=
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
management-server-enabled=false
max-players=20
use-native-transport=true
enable-status=true
management-server-secret=w3Qw6WNF3sMSWlNPbE0FKZTt5iFEQ2SSX31xpoRN
online-mode=false
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
management-server-allowed-origins=
resource-pack-prompt=
server-ip=127.0.0.1
allow-nether=true
bug-report-link=
server-port=25566
enable-rcon=false
sync-chunk-writes=true
resource-pack-id=
op-permission-level=4
accepts-transfers=false
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
management-server-tls-keystore-password=
simulation-distance=10
player-idle-timeout=0
rcon.password=
status-heartbeat-interval=0
force-gamemode=false
debug=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
region-file-compression=deflate
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
enable-code-of-conduct=false
max-world-size=29999984
