#Minecraft server properties
#Sun Sep 20 10:51:48 TRT 2026
enable-jmx-monitoring=false
level-seed=
management-server-port=0
rcon.port=25575
enable-command-block=false
gamemode=survival
enable-query=false
generator-settings={}
enforce-secure-profile=false
level-name=world
text-filtering-version=0
motd=Nova Skyblock | Yildiz Zindani ve Kozmik Kasalar
pause-when-empty-seconds=0
management-server-host=localhost
query.port=25566
management-server-tls-enabled=true
management-server-tls-keystore=
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=normal
network-compression-threshold=-1
max-tick-time=60000
require-resource-pack=false
management-server-enabled=false
max-players=100
use-native-transport=true
enable-status=true
management-server-secret=
online-mode=false
allow-flight=true
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=8
management-server-allowed-origins=
resource-pack-prompt=
server-ip=127.0.0.1
allow-nether=true
bug-report-link=
server-port=25566
enable-rcon=false
sync-chunk-writes=false
resource-pack-id=
op-permission-level=4
accepts-transfers=false
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
management-server-tls-keystore-password=
simulation-distance=6
player-idle-timeout=0
rcon.password=
status-heartbeat-interval=0
force-gamemode=false
debug=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
region-file-compression=deflate
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
enable-code-of-conduct=false
max-world-size=29999984
