#Minecraft server properties
#Mon Jul 27 17:33:22 GMT+03:00 2026
allow-flight=false
allow-nether=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
debug=false
difficulty=peaceful
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=adventure
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=MainLobby
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=60
max-tick-time=60000
max-world-size=29999984
motd=Main Lobby Of The BANNANCRAFT
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25555
simulation-distance=2
spawn-animals=false
spawn-monsters=false
spawn-npcs=true
spawn-protection=29999984
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=12
white-list=false
